apiVersion: v1
kind: Service
metadata:
  name: upbank-ui-svc
  namespace: frontend
  labels:
    project: upbank-lab
    app: upbank-ui
    environment: prod
spec:
  selector:
    app: upbank-ui
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upbank-ui-ingress
  namespace: frontend
  labels:
    project: upbank-lab
    app: upbank-ui
    environment: prod
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-southeast-2:097922957316:certificate/d7a06dc6-9f53-4f04-9bde-1c1a6a79676a"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/load-balancer-name: upbank-ui-alb
spec:
  ingressClassName: alb
  rules:
    - host: upbank-lab.alanlima.cloud
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: upbank-ui-svc
               port:
                 number: 80