name: infra-apply

on:
  push:
    branches:
      - main
    paths:
      - 'infra/terraform/prod**'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: Apply Terraform Plan to Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.2

      - name: Fix Terraform permissions
        run: |
          if [ -n "$TERRAFORM_CLI_PATH" ]; then
            chmod +x "$TERRAFORM_CLI_PATH/terraform" || true
          fi
          which terraform
          terraform version

      - name: Terraform Init
        working-directory: ./infra/terraform/prod
        run: terraform init

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: terraform-prod-plan
          path: ./infra/terraform/prod

      - name: Verify Plan Artifact
        working-directory: ./infra/terraform/prod
        run: |
          if [ ! -f tfplan ]; then
            echo "❌ Error: tfplan artifact not found!"
            exit 1
          fi
          echo "✅ tfplan artifact downloaded successfully"
          ls -lah tfplan

      - name: Terraform Apply
        working-directory: ./infra/terraform/prod
        run: terraform apply tfplan
