name: infra
on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/terraform**'
  push:
    branches:
      - '**'
    paths:
      - 'infra/terraform**'
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    name: Run Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          # role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.2

      - name: Fix Terraform permissions
        run: |
          if [ -n "$TERRAFORM_CLI_PATH" ]; then
            chmod +x "$TERRAFORM_CLI_PATH/terraform" || true
          fi
          which terraform
          terraform version

      - name: Terraform Init
        working-directory: ./infra/terraform/prod
        run: terraform init

      - name: Terraform Validate
        working-directory: ./infra/terraform/prod
        run: terraform validate
      
      - name: Terraform Format Check
        working-directory: ./infra/terraform/prod
        run: terraform fmt -check -recursive
      
      - name: Create terraform.tfvars file
        shell: bash
        run: |
          cat <<EOF > ./infra/terraform/prod/terraform.tfvars
          app_name = "upbank-lab"
          environment = "prod"
          eks_admin_user_name = "${{ vars.EKS_ADMIN_USER_NAME }}"
          EOF
      - name: Terraform Plan
        working-directory: ./infra/terraform/prod
        run: terraform plan -out tfplan -var-file=terraform.tfvars

      - name: Post Terraform Plan Comment in PR
        uses: towardsthecloud/terraform-plan-pr-commenter@v1
        with:
          planfile: tfplan
          working-directory: ./infra/terraform/prod
          aws-region: ap-southeast-2

  apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.2

      - name: Fix Terraform permissions
        run: |
          if [ -n "$TERRAFORM_CLI_PATH" ]; then
            chmod +x "$TERRAFORM_CLI_PATH/terraform" || true
          fi
          which terraform
          terraform version

      - name: Terraform Init
        working-directory: ./infra/terraform/prod
        run: terraform init

      - name: Create terraform.tfvars file
        shell: bash
        run: |
          cat <<EOF > ./infra/terraform/prod/terraform.tfvars
          app_name = "upbank-lab"
          environment = "prod"
          eks_admin_user_name = "${{ vars.EKS_ADMIN_USER_NAME }}"
          EOF

      - name: Terraform Apply
        working-directory: ./infra/terraform/prod
        run: terraform apply -auto-approve -var-file=terraform.tfvars
